name: Update README activity

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update activity section
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Recent Activity
        uses: Readme-Workflows/recent-activity@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}