settings:
  username: "FDE-1"
  commit_msg: "⚡ Update README with recent activity"
  max_lines: 5
  readme_file: "./README.md"

  date:
    timezone: "Europe/Brussels"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"

  messages:
    push:           "⬆️ Pushed {AMOUNT} commit(s) to {REPO}"
    issue_opened:   "❗ Opened issue {ID} in {REPO}"
    issue_closed:   "✔️ Closed issue {ID} in {REPO}"
    pr_opened:      "💪 Opened PR {ID} in {REPO}"
    pr_merged:      "🎉 Merged PR {ID} in {REPO}"
    pr_closed:      "❌ Closed PR {ID} in {REPO}"
    create_repo:    "📔 Created new repository {REPO}"
    fork:           "🍴 Forked {REPO}"
    star:           "⭐ Starred {REPO}"