name: Update README activity

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update activity section
    permissions:
      contents: write

    steps:
      # - name: Checkout repo             
      #   uses: actions/checkout@v4
        
      - name: Recent Activity
        uses: jamesgeorge007/github-activity-readme@master
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          MAX_LINES: 5
          CONFIG_FILE: "⚡ Update README with recent activity"